name: ecobeam_test
description: "An Ecobeam app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/sans/OpenSans-Bold.ttf
        - asset: assets/fonts/sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/sans/OpenSans-Italic.ttf
        - asset: assets/fonts/sans/OpenSans-Light.ttf
        - asset: assets/fonts/sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/sans/OpenSans-Medium.ttf
        - asset: assets/fonts/sans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/sans/OpenSans-Regular.ttf
        - asset: assets/fonts/sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/sans/OpenSans-SemiBoldItalic.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-Bold.ttf
        - asset: assets/fonts/lora/Lora-BoldItalic.ttf
        - asset: assets/fonts/lora/Lora-Italic.ttf
        - asset: assets/fonts/lora/Lora-Medium.ttf
        - asset: assets/fonts/lora/Lora-MediumItalic.ttf
        - asset: assets/fonts/lora/Lora-Regular.ttf
        - asset: assets/fonts/lora/Lora-SemiBold.ttf
        - asset: assets/fonts/lora/Lora-SemiBoldItalic.ttf